import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import "./Home.css";
import MainCarousel from "../../components/MainCarousel/MainCarousel";
import "../../Global.css";
import Search from "../../components/Search/Search";
import LastCarousel from "../../components/LastCarousel/LastCarousel";
import Contact from "../../components/Contact/Contat";
const Home = () => {
    return (_jsxs("div", { className: "d-flex flex-column justify-content-center align-items-center", children: [_jsxs("div", { className: "d-sm-none", children: [_jsx("div", { className: "w-100 mt-1 mb-1 d-flex align-items-center justify-content-center", style: { backgroundColor: "#B84644", height: "75px" }, children: _jsx("h1", { className: 'fs-1 ms-3 text-light text-center', children: "Bienvenido!" }) }), _jsxs("div", { className: "d-flex flex-column align-items-center overflow-hidden position-relative w-100 justify-content-center", style: { height: "85vh" }, children: [_jsx("img", { className: "position-absolute w-100 h-100 object-fit-cover", src: "/images/homebg.webp", alt: "", style: { opacity: ".3", zIndex: "0" } }), _jsx("img", { className: "mt-5 mb-5 z-1", src: "/images/homelogo.webp", alt: "" }), _jsx("p", { className: "fst-italic z-1", children: _jsx("b", { children: "\"Donde nacen tus sue\u00F1os\"" }) })] })] }), _jsx("div", { className: "w-100 mt-1 mb-1 d-flex align-items-center", style: { backgroundColor: "#B84644", height: "75px" }, children: _jsx("h1", { className: 'fs-1 ms-3 text-light', children: "Propiedades destadacas." }) }), _jsx("div", { className: "container w-100 mt-3 mb-3", children: _jsx(MainCarousel, {}) }), _jsx("div", { className: "w-100 mt-1 mb-1 d-flex align-items-center", style: { backgroundColor: "#B84644", height: "75px" }, children: _jsx("h1", { className: 'fs-1 ms-3 text-light', children: "Encontr\u00E1 tu propiedad." }) }), _jsx("div", { className: "container w-100 mt-3 mb-3", children: _jsx(Search, {}) }), _jsx("div", { className: "w-100 mt-1 mb-1 d-flex align-items-center", style: { backgroundColor: "#B84644", height: "75px" }, children: _jsx("h1", { className: 'fs-1 ms-3 text-light', children: "\u00DAltimas publicaciones" }) }), _jsx("div", { className: "container w-100 mt-3 mb-3", children: _jsx(LastCarousel, {}) }), _jsx("div", { className: "w-100 mt-1 mb-1 d-flex align-items-center", style: { backgroundColor: "#B84644", height: "75px" }, children: _jsx("h1", { className: 'fs-1 ms-3 text-light', children: "Comunicate con nosotros" }) }), _jsx("div", { className: "container w-100 mt-3 mb-3", children: _jsx(Contact, {}) })] }));
};
export default Home;
